### PR TITLE
Fix IsMemberCategoricalFixup for large bin arrays

### LINKED ISSUE #63: IsMemberCategoricalFixup doesn't handle arrays larger than 2bn
The `IsMemberCategoricalFixup()` function, used by rt.ismember() on Categoricals, blindly casts array sizes to int32, and overflows producing garbage when array sizes are larger than 2bn.

Part of rtosholdings/riptable#243

### PR DESCRIPTION
**Pull request by OrestZborowski-SIG**
Properly maps bin arrays larger than 2bn entries.
Still requires unique count to fit in 32-bit, which is enough for
2bn unique categoricals.
Fixes #63
Fixes rtosholdings/riptable#243

### CODE REVIEW

File: src/HashFunctions.cpp [hunk 1]
```diff
@@ -320,11 +323,19 @@ void FindFirstOccurence(T * pArray2, int32_t * pUnique1, int32_t * pReIndex, int
     for (int32_t i = 0; i < unique1Length; i++)
     {
         int32_t val = pUnique1[i];
+        if (val == invalid)
```
Comment (jack-pappas) [inline src/HashFunctions.cpp:326]: I understand this approach of checking for an invalid value is used throughout the codebase; but when possible going forward, I think we ought to prefer using the templated ``invalid_for_type<>::is_valid(x)`` type / static method from the ``missing_values.h`` header. The templated approach provides a uniform API that handles both integers and floating-point types, and will allow some code throughout _riptide_cpp_ to be consolidated where it varies only due to a difference in how it checks for invalids for different types.

File: src/HashFunctions.cpp [hunk 2]
```diff
@@ -439,13 +459,20 @@ PyObject * IsMemberCategoricalFixup(PyObject * self, PyObject * args)
                            &unique2Length, &baseoffset1, &baseoffset2))
         return NULL;
 
-    int32_t arraySize1 = (int32_t)ArrayLength(inArr1);
-    int32_t arraySize2 = (int32_t)ArrayLength(inArr2);
-    int32_t arraySizeUnique = (int32_t)ArrayLength(isMemberUnique);
+    int64_t const arraySize1 = (int64_t)ArrayLength(inArr1);
```
Comment (jack-pappas) [inline src/HashFunctions.cpp:462]: ``ArrayLength`` already returns ``int64_t``, so these casts aren't necessary now like they were before.
